### ISSUE TITLE
notify users for empty values

### ISSUE THREAD

**Issue by haozhu233** [ropensci/skimr#12]
For `""` or `"  "`, notify users that they might need to do a data cleaning before summarizing.

**Comment by mine-cetinkaya-rundel** [comment]
Good idea! On that note, I would also suggest adding `"."` to this list, as it's another commonly used `NA`.

There is also the issue of using a `"9+"` pattern, but that might be too dicey to get into.

**Comment by elinw** [comment]
Skim will definitely let you know that you need to do cleaning like this and then you can skim again to make sure it worked correctly.

**Comment by elinw** [comment]
I don't know how far down this road we want to go but counting the number of strings that are all white space e.g. "     "  could be a useful thing, especially since that can be deceiving. I think we need to discuss it.

**Comment by elinw** [comment]
I think that detecting all white space strings in character vectors would be a good enhancement and makes more sense than trying to pick an arbitrary number of spaces to catch.
