### ISSUE TITLE
Convert skim_v tests to skim tests

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#242]
`Skim_v()`was changed to be internal and skim.default() now handles individual vectors. It would be preferable to move the testing to the exported method.  The major difference is that the skim method returns a full dataframe.

**Comment by michaelquinn32** [comment]
When converting, it would be nice to update the format to match that in skim as well. Using tribble was awesome for demoing the expected out. Testing column-wise is just easier to maintain.

**Comment by elinw** [comment]
Closing this since all the tests are redone in v2.  Though we still may want to do some work there.
