### ISSUE TITLE
Print spark histograms in Emacs ESS

### ISSUE THREAD

**Issue by vinhdizzo** [ropensci/skimr#246]
Hi,

Any thoughts on how best to get Emacs ESS to print the spark histograms on Windows?  My guess is `Sys.setlocale("LC_CTYPE", "Chinese")` is still needed.  Thank you!

**Comment by elinw** [comment]
Did you try it?

**Comment by vinhdizzo** [comment]
Yes, I did, but it did not print properly. Curious if anyone got it to work. My guess is the font also needs to be changed in Emacs. I will do some research on how to do this. Will try deja Vu sans when I get the font installed.

**Comment by elinw** [comment]
Okay when you get a chance if you can give some screen shots that would be great.

**Comment by vinhdizzo** [comment]
Here's my update.  I am using the DejaVu Sans font in emacs via the following setting in my `init.el` file: `(set-face-attribute 'default nil :font "DejaVu Sans-12")`.

This is the display in emacs ESS:
![image](https://user-images.githubusercontent.com/114053/35071290-1002c15c-fb95-11e7-93f9-46af7e6b6532.png)

This is the display after setting the Chinese locale:
![image](https://user-images.githubusercontent.com/114053/35071320-2ca4ba9a-fb95-11e7-9b89-6e0d842f110e.png)


Note that I also cannot get the display correct in the regular R windows console (not RStudio).  Any thoughts?

**Comment by elinw** [comment]
Thanks!
I found an old document here http://dirk.eddelbuettel.com/code/ess/ess-manual.pdf
that says

> ESS[R]: now works better when UTF-8 locale is active; in particular, you get
> correct directional quotes in R’s startup message for R-devel (unstable development
> version of R 2.1.0) when using environment variables LANGUAGE=en@quot
> LC ALL=en US.UTF-8

Do you want to try that? I see other people with unanswered questions about this issue. Somehow it must be applying the format() function again.

**Comment by vinhdizzo** [comment]
@elinw I had previously responded to your latest response but just realized it never went through.  In short, I do have those environment variables set up but no cigar.

**Comment by elinw** [comment]
I'm going to close this since no progress in over a year and it is basically a part of the larger issue of UTF-8 on windows.
