### ISSUE TITLE
consider knit_print instead of current kable/pander implementation?

### ISSUE THREAD

**Issue by haozhu233** [ropensci/skimr#249]
This is just an idea. The current approach of creating a copy of `kable` & `pander` function seems to be a little risky regarding function namespace. How about just using `knitr::knit_print()` to create a print method in rmd? It won't work in shiny though.

**Comment by elinw** [comment]
We don't make a copy of pander() since it is a generic, we just implement a method for our class. Kable on the other hand  you are right that knit_print is a generic.  We create a kable generic. 
https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html

**Comment by michaelquinn32** [comment]
https://github.com/yihui/knitr/issues/1493

**Comment by haozhu233** [comment]
Hmm, I mean why do we need to use `kable` to print it in rmarkdown? The end result is not a table.....

**Comment by michaelquinn32** [comment]
All apologies, but I just had time read the vignette to the end. This looks like a big improvement. And it might let us drop knitr/ pander support in the next version.

Thanks!

**Comment by elinw** [comment]
I think there are people who like to use pander (which at least in the past has had extra features like nice management of split tables and split lines in titles) so I wouldn't necessarily drop it. The whole issue of how to manage very big skim prints (100s of variables) is definitely going to be an issue.

**Comment by elinw** [comment]
I think that one thing in my mind at least is that people are used to using kable().   In some ways we would be better off making the print be a table but that ship has really sailed. It is also (for better or worse) more typical of the tidyverse to leave everything as a tibble/data frame which actually tends to make correctly structured printing more difficult.

**Comment by michaelquinn32** [comment]
Using `knit_print` is the preferred approach in v2.
