### ISSUE TITLE
Re-arrange print order when using groups?

### ISSUE THREAD

**Issue by vinhdizzo** [ropensci/skimr#264]
Hi,

I have a use case for skimr: to assess balance of covariates by groups.  One could get summaries by:
```r
iris %>% dplyr::group_by(Species) %>% skim()
```

However, the output is ordered by the groups, then the variables.  To more easily compare, I would like to re-order the printout by variable, then groups, as in:
```r
iris %>% dplyr::group_by(Species) %>% skim() %>% dplyr::arrange(variable, Species)
```
This does not print correctly as it is no longer a `skim_df` object.  Is there a way to get this object to print as in `print.skim_df`?  Thank you.

**Comment by elinw** [comment]
I would suggest with skim_to_wide or skim_to_list.  Once you do those you have a combined big single wide data frame or a list of wide data frames.  You can then sort those as you wish.   

I'm not sure but another option may be to do the arrange() and then force %>% print.skim_df().  I haven't tried it though.  Unfortunately arrange only does sorting by alphabet.

It's an interesting thought to provide that option, someone else asked to have the option to be not alphabetical for the variables so it seems as though sorting is a good idea to consider for 1.1.   One thing is to notice how it gets more complex when you have multiple types e.g. say in the CO2 data set.  So you really need type, variable,group  and type, group, variable.

**Comment by elinw** [comment]
After all this time I did actually figure out a way to do this.
```
       s<- iris %>% dplyr::group_by(Species) %>% skim() %>% dplyr::arrange(variable, Species)
      class(s) <- c( "skim_df", class(s))
      s
```

**Comment by jzadra** [comment]
Neither of those seem to work for me, they produce the default sorting of Species, then variable.

**Comment by elinw** [comment]
Okay here is a new way.  

```
s <- iris %>% dplyr::group_by(Species) %>% skim_to_list()
s[[1]] %>% dplyr::arrange(variable)

```

Of course you would have to do this for each sub table, but you could write a function to do that.

  You can also do

```
s <- iris %>% dplyr::group_by(Species) %>% skim_to_wide() %>% dplyr::arrange(variable)
```

And in that case use `filter()` and `select()`  to rows and columns presuming you don't want all the NA columns if your data has multiple data types.

**Comment by elinw** [comment]
In the v2 version of skimr the  skim_df object is a wide data frame that you can then use dplyr to manipulate, so you would be able to change the group_by() ordering or to use arrange().   The only thing to remember is that you get a separate sub table printed for each type so the default skim print would potentially produce a lot of tables.
