### ISSUE TITLE
Onboarding: API - long, wide, list, etc

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#290]
Both reviewers raise the issue of the difference between what `print.skim_df()` displays and the `skim_df` object.  While a gap between these is not uncommon (e.g. `View(freeny.y)` versus `print(freeny.y)`)  (also of course in the outputs of many statistical functions).  Since the original goal of skimr was originally to display beautifully in the console  and to both consume and return piped/pipe-able data the focus on a tidy, long data set makes the most sense. But it's  basically inevitable that people are going to see the formatted horizontal output and want to do more than display it in the console.  And to complicate it more, sometimes they are going to want to work with the formatted values to make nice custom displays and sometimes they are going to want the numeric values . 

Basically we currently provide two workarounds which are not completely satisfactory. `skim_to_wide()`  creates the sparse data.frame (unless all of the variables are of the same class) with one row per variable and lots of NAs and can be piped.  `skim_to_list()` which is  a named list by type which could be further manipulate outside of the pipe model. Each of the data frames in the list could, however, be piped and also with purr or lapply you could create separate tables etc.

So that leaves us with the question of what is the best way to be helpful to users but without giving up the basic goal of beautiful display on the console.

I think we may be making the problem somewhat more complex than we need to. We might want to consider  _why_  people find it so helpful to envision doing what they are trying to do, why they can't do it other ways,  then think about what the right way to get there is.

At this point it seems like it is more a discussion topic rather than time to start coding (except maybe prototypes).

**Comment by elinw** [comment]
One question is whether we should give the option to get numeric data rather than what is printed (formatted data). And if we did that would that be via an option in those functions? Or separate functions?

**Comment by elinw** [comment]
An additional option to consider if we are looking at this is Hadley's suggestion for a different kind o long data frame https://github.com/ropenscilabs/skimr/issues/4  which I think would actually have two list columns at this point, one for numeric and one for formatted.

**Comment by elinw** [comment]
I'm going to switch this to the skimr v2 tag.

**Comment by michaelquinn32** [comment]
Wide and sparse is now the v2 approach. Feel free to reopen if we need to discuss more.
