### ISSUE TITLE
Change the appearance of the displayed results

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#325]
@jimhester @jenniferthompson @michaelquinn32 
Our ROpenSci reviewers feel that the potential confusion of the long skim_df object and the wide print display makes things difficult.  Changing the default object is something that we're  discussing in a separate issue but would break the API in a major way.   However it was also suggested that as an interim approach we could change the print display to make it more clear that it is not a single data frame.   

Here are two simple ways we could do this in the console.  Please let us know if you think this will do the trick for now or if it should be more complex.  One thing is that trying to figure out how wide the screen is etc is not simple so doing this (which just focuses on  separating the separate sub tables more by more clearly highlighting the separate titles).
![screen shot 2018-04-08 at 8 39 35 pm](https://user-images.githubusercontent.com/754813/38623628-25791f92-3d74-11e8-94bb-b4d00d0c150d.png)
![screen shot 2018-04-08 at 8 36 59 pm](https://user-images.githubusercontent.com/754813/38623630-25c7a388-3d74-11e8-9808-590775c4a22e.png)

**Comment by jimhester** [comment]
You may want to look into https://github.com/r-lib/cli, it is lots of functions for displaying on screen, including screen width aware boxes etc as well as a `console_width()` function to get the width of the current console.

**Comment by elinw** [comment]
@jimhester Thanks!

**Comment by elinw** [comment]
I'm also toying with the idea of putting the summary.skim_df() output at the top instead of the abbreviated version.

**Comment by elinw** [comment]
Okay I sent up  a PR showing what it might look like using cli. https://github.com/ropenscilabs/skimr/pull/326  I really hesitate to overdo it but I think the rule probably does help. 
Screen shots (one shows a narrower window, one 80 columns):
![screen shot 2018-04-14 at 6 51 19 pm](https://user-images.githubusercontent.com/754813/38773217-41ae90ea-4015-11e8-93d2-12ea7e1d9523.png)
![screen shot 2018-04-14 at 6 49 50 pm](https://user-images.githubusercontent.com/754813/38773218-41bca5fe-4015-11e8-974d-9cded256c9c7.png)

**Comment by michaelquinn32** [comment]
Thanks for putting so much work into updating this. FWIW, this is my favorite among the versions that you've shown. Very nice!

**Comment by jimhester** [comment]
Yeah I like it!

**Comment by elinw** [comment]
Great so I've got the PR, and I think I'll go ahead and merge it.

**Comment by jenniferthompson** [comment]
This last version is my favorite too, @elinw! My onky suggestion would be to consider adding a line of white space before each variable type to give the eyes a break.
