### ISSUE TITLE
Standardize package name format in README

### ISSUE THREAD

**Issue by pkq** [ropensci/skimr#337]
Most occurrences of the package name in the README are of the format `skimr`, but several do not follow this format. Per the contributing guidelines, I'm opening this companion issue alongside a PR to make these changes.

**Comment by elinw** [comment]
Yes the html is `<code>skimr</code>`  which would be confusing to a screen reader since it is not code of any kind.  I wonder if it should really be `<cite></cite>`? https://www.w3schools.com/tags/tag_cite.asp

**Comment by elinw** [comment]
Would you want to update the PR? I'm fine with the lower case branding.

**Comment by pkq** [comment]
Sure thing. Just pushed a new commit that uses the cite tag. I noticed after pushing the commit that re-knitting the README changed some other formatting as well. If that's an issue, let me know, and I'll try to undo that.

**Comment by elinw** [comment]
fixed in develop.
