### ISSUE TITLE
Typo in vignette "Using skimr"

### ISSUE THREAD

**Issue by AndreaPi** [ropensci/skimr#354]
Typo in vignette [Using skimr](https://github.com/ropensci/skimr/blob/master/vignettes/Using_skimr.Rmd), line 175:

> - `skim_to_list()` returns a **nqmed** list of the wide data frames for each data

nothing serious, but maybe worth a fix. Sorry for not making a PR, but on holiday now so I've got limited access to Github. Cheers!

**Comment by elinw** [comment]
Thanks! I will update.
