### ISSUE TITLE
warning with `R 3.6.0`

### ISSUE THREAD

**Issue by IndrajeetPatil** [ropensci/skimr#357]
With the development version of `R 3.6.0` I am getting the following warning once per session (because overwriting `S3` methods has become verbose). 
```
Registered S3 method overwritten by 'skimr':
  method      from  
  print.spark pillar
```
It will be nice if `skimr` can be changed so that these `warnings` aren't displayed to the user who might get confused.

**Comment by elinw** [comment]
Okay I'll have to look into how to make that quieter.

**Comment by elinw** [comment]
Actually I think this is a setting that should be done on the user side, because the reason this was changed was to ensure that users know when this happens.  For example you can use  `suppressPackageStartupMessages(library(skimr))`.

**Comment by IndrajeetPatil** [comment]
This will work for the user, but this is still an issue for other package developers. For example, I'm importing `skimr` for my package and every time it is loaded, this warning is produced. 

```
==> devtools::check(args = c('--as-cran'))

Updating ggstatsplot documentation
Writing NAMESPACE
Loading ggstatsplot
Registered S3 method overwritten by 'dplyr':
  method               from  
  as.data.frame.tbl_df tibble
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Registered S3 method overwritten by 'skimr':
  method      from  
  print.spark pillar
Writing NAMESPACE
```

Currently, this is not an issue because `R 3.6.0` is still in development and the users will not see this `warning`. But, in the long run, I'd strongly prefer if users of my package don't see this warning since I don't think the message about `S3 method` registration is going to be of much interest to a general user.

**Comment by elinw** [comment]
I think we introduced that to solve a particular problem when pillar was changing (also related to some of the issues with the histograms), but possibly it would work now if we deleted.

**Comment by elinw** [comment]
I think the only solution may be to rename it since I don't think that the tidyverse will go back to exporting it. I wonder how many people are actually using it.

**Comment by elinw** [comment]
Actually with v2 we don't print.spark and longer so this issue should go away.
