### ISSUE TITLE
Deal with rlang and dplyr soft deprecations

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#369]
- [x] list_len
- [x] funs
- [x] !!!
- [x] set_names 
- [x] set_attrs

 Reference list: https://rlang.r-lib.org/reference/lifecycle.html

Warning messages:
1: `list_len()` is soft-deprecated as of rlang 0.2.0.
Please use `new_list()` instead
This warning is displayed once per session. 
2: Unquoting language objects with `!!!` is soft-deprecated as of rlang 0.3.0.
Please use `!!` instead.

  # Bad:
  dplyr::select(data, !!!enquo(x))

  # Good:
  dplyr::select(data, !!enquo(x))    # Unquote single quosure
  dplyr::select(data, !!!enquos(x))  # Splice list of quosures

**Comment by elinw** [comment]
Here's information for the funs() deprecation

https://github.com/tidyverse/dplyr/issues/4150

**Comment by elinw** [comment]
Also purrr::set_names()  is replaced by rlang::set_names.

**Comment by elinw** [comment]
@michaelquinn32 do we think we are set on these?

**Comment by michaelquinn32** [comment]
I think we're set on all.
