### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#370]
Right now skimr gets very slow for large data sets. We should try to speed things up where possible. 

This is true for v1 and v2 but v2 is slower on some benchmarks.

**Comment by michaelquinn32** [comment]
The first big step will be to run profvis over some scenarios to see where we're spending a lot of compute time.

https://rstudio.github.io/profvis/

My guess is that the cost is in the call to summarize_all for each variable, which is then unnested.
* https://github.com/ropensci/skimr/blob/627214fdea54bea628750f7b960ef49c4f49640a/R/skim_with.R#L196
* https://github.com/ropensci/skimr/blob/627214fdea54bea628750f7b960ef49c4f49640a/R/skim_with.R#L97

Speeding this up would involve reducing the number of calls to `summarize_all` and reducing the implicit number of joins in `unnest`

**Comment by GShotwell** [comment]
I can take a look at this one I think. Do you have some examples of things which you're finding slow? Also it would be great to have targets for how fast we want it to be. 

A first run of profvis seems to suggest that the slowness might be happening in the summary functions themselves. Is it worth adding a logging argument to skim to let the user get some transparency into which of the summary functions are running slowly?

**Comment by michaelquinn32** [comment]
Thanks for hopping in Gordon!

I think we are on the same page. The summary functions are being called too many times by the unnecessary extra calls of summarize_all().

I've opened a new branch (v2-performance), which will implement my ideas about summarize_all(). I'd be happy to accept any other performance ideas that you might have there.

**Comment by michaelquinn32** [comment]
Hi Gordon!

The PR has some initial changes for improving performance. I had to use two different machines for these benchmarks (long story), but here's what I got.

v1
```
> microbenchmark(skim(CO2), skim(diamonds), skim(mtcars), skim(iris))
Unit: milliseconds
           expr       min        lq      mean    median        uq       max neval cld
      skim(CO2)  29.64275  31.37928  34.41101  32.39665  34.40181  56.32438   100 a
 skim(diamonds) 362.66016 403.76066 480.75501 447.87473 566.36269 721.54695   100   c
   skim(mtcars)  65.96315  69.47333  76.90582  72.02940  86.56685  99.31945   100  b
     skim(iris)  29.36607  31.50726  36.68106  33.28038  37.22499  59.61407   100 a
```

v2
```
> microbenchmark(skim(CO2), skim(diamonds), skim(mtcars), skim(iris))
Unit: milliseconds
           expr       min        lq      mean    median        uq      max neval
      skim(CO2)  49.84370  51.86709  56.01901  53.54249  56.61397 145.6358   100
 skim(diamonds) 281.78280 289.15416 319.83532 295.02698 375.80182 391.6615   100
   skim(mtcars) 115.98924 119.84997 123.85696 123.06421 125.50996 206.0906   100
     skim(iris)  49.24863  52.79364  56.01051  54.80406  57.18373 137.4787   100
```

**Comment by michaelquinn32** [comment]
I'm closing this for now. Feel free to take this up in another branch!
