### ISSUE TITLE
For datasets with many columns, skimr v2 does not behave as documented

### ISSUE THREAD

**Issue by GegznaV** [ropensci/skimr#376]
Argument `...` documentation of `skim()` says: "...  Columns to select for skimming. When none are provided, the default is to skim **all columns**". But for large dataset this is not true:

```r
 DAAG::rockArt %>% skimr::skim()
```
![image](https://user-images.githubusercontent.com/12725868/51448123-f2c0d100-1d2c-11e9-8625-c416df6bf4e0.png)
Of course, I gave an extreme example, but usually, I expect all columns to be summarized.

Related issue – not all columns with summary statistics are printed for narrow consoles:

![image](https://user-images.githubusercontent.com/12725868/51448489-b347b400-1d2f-11e9-88a6-62008e824f77.png)

As I understand, skim uses `print.tbl` method internally. So, maybe setting `n = Inf` and `width = Inf` would help? E.g.:
```r
mtcars %>% as_tibble() %>% print(n = Inf, width = Inf)
```

Maybe skim could accept these parameters directly. Otherwise default values could be set to `Inf`? E.g.:

```r
DAAG::rockArt %>% skimr::skim(n = Inf, width =Inf)
```

**Comment by GegznaV** [comment]
One more related issue is truncated variable names if window is not wide enoufg or if the names are long enough.

![image](https://user-images.githubusercontent.com/12725868/51448865-facf3f80-1d31-11e9-8c22-409d1fbbf218.png)

**Comment by GegznaV** [comment]
I found out that this issue could be solved by setting tibble options:

```r
op <- options(tibble.print_min = Inf, tibble.width = Inf)
```

But the main point is that the behavior should be well **documented** as for regular user the solution may not be obvious. Even the behavior may not be obvious.

**Comment by GegznaV** [comment]
I appreciate your work. Hope, skim v2 will be released soon.

**Comment by elinw** [comment]
I think we definitely need to document how to set tibble options.  The data are all there in  the object but the tibble print can hide it.   I know that console printing is one motivation for tibbles but for skimr it's really frustrating not to get the whole row.

**Comment by elinw** [comment]
I think we an close this now.

**Comment by michaelquinn32** [comment]
a36073527fc835fc96b78e3210a664d52caa1e8b makes sure that all rows and columns print by default. It's set by arguments to `print`, similar to tibble, but with `Inf` as the default.

I still think there is a better way to communicate ideal print setups. For example I think `options(width = 85)` is better than just 80 characters. We'll leave this open for now.

**Comment by elinw** [comment]
@michaelquinn32 can you also look at the related https://github.com/ropensci/skimr/issues/384 ? I'm not sure if it is still an issue with the way the settings are done now ... also I'm not sure if it might be a tibble print bug.
