### ISSUE TITLE
Consider name spacing `type` and `variable`

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#389]
It's probably somewhat typical for there to be a variable name of type and also sometime of variable.  We should probably change these names to something like skim_type and skim_variable. This wasn't an issue in v1.

**Comment by slhck** [comment]
I just found `skimr` and thought it was awesome! But I couldn't figure out why my grouping wouldn't work … I had  `type` variable that I wanted to group by.

**Comment by michaelquinn32** [comment]
Glad you're liking it Werner, and thanks for the feedback!

This will be something we look deeper at in v2 of the package.

Just to be clear, did you have something like this?

```
data.frame(
    type = c("a", "b"),
    value = c(1, 2),
    strings = c("Y", "N)) %>%
  dplyr::group_by(type) %>%
  skim()
```

**Comment by slhck** [comment]
Yes, that's exactly what happened. I just had a gut feeling that special variable names could cause this (I was simultaneously working on a Rails project where `type` is a special attribute), so I came looking here.

I'm not sure about what your plans are for releasing v2 – in the meantime, do you think it would be viable to print a warning for users if the input data frame contains a column with a reserved name?

**Comment by elinw** [comment]
V2 we hope will be soon, we've made  a ton of progress but we also have to wait for the dplyr release since we have a new minimum version.  I think printing a warning is a good idea, let me see what that would take.

**Comment by elinw** [comment]
If we name space the spark plots also we could address this issue in R 3.6 https://github.com/ropensci/skimr/issues/357  .  I'd say let's do skim_type, skim_variable and skim_spark.

**Comment by michaelquinn32** [comment]
#399 Fixes this partially

**Comment by elinw** [comment]
@michaelquinn32 What is left to do?

**Comment by michaelquinn32** [comment]
I think we're done after our different sets of changes.
