### ISSUE TITLE
Handle 0 row data sets gracefully

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#393]
Currently a 0 row data set errors.  We should decide what the right result should be (just the summary? the variable names? an error/warning/message?)

**Comment by elinw** [comment]
It's not just from dplyr ... you can mess up creating a data set in many ways and get 0 rows; it has an ugly failure message.  I agree that if someone in the context of piping with dplyr deletes everything then normal dplyr handling is the way to go.

**Comment by michaelquinn32** [comment]
Good point. Then let's make the fix a part of the type checking that I just added.

**Comment by elinw** [comment]
Closing as this has been addressed.
