### ISSUE TITLE
Printing in Jupyter notebook

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#395]
This was raised on StackOverflow
https://stackoverflow.com/questions/54541755/unable-to-reproduce-output-from-skimr-vignette

I think it probably won't be an issue in v2 but I'm not sure.

**Comment by elinw** [comment]
He said skim(iris) %>% print(skim_df()) worked ... I'm not sure if this is about jupyter notebook or something else.

**Comment by michaelquinn32** [comment]
`skimr` returns something quite different than what it prints. You can see the difference by comparing:
https://github.com/ropensci/skimr/blob/jupyter/skimr_in_jupyter.ipynb

Within Jupyter, when you return a data frame at the end of a cell, the `repr` package does some nice things to it and makes it beautiful.
https://github.com/IRkernel/repr/blob/master/R/generics.r

We should consider exporting repr_html.skim_df, repr_latex.skim_df and repr_text.skim_df methods or a pull request to that package.

**Comment by michaelquinn32** [comment]
The way we print a `skim_df`, which requires multiple calls, means that we can only support standard output in Jupyter for now. Multiple prints was pointed out in #408. I still stand by the approach that we have, but we'll have to be aware of this if we eventually want html in Jupyter notebooks.
