### ISSUE TITLE
Print methods and distorted formatting of `skim()` output

### ISSUE THREAD

**Issue by GegznaV** [ropensci/skimr#408]
I installed the newest `skimr` version by using:
```r
devtools::install_github("ropenscilabs/skimr@v2")
```
As #341 is closed and #383 is open, I thought there would not be any important changes in v2. But I noticed that the output of `skim()` changed a few days ago. 

By using `skimr`, I aim to get the impression of my data at one glance without tiring analysis of the output (I mean the form of how the output is presented/printed). I also would like the output of `skim()` to be as easy to understand for less technical people as possible (as I teach people like those).
I see, that you, guys, are working hard on `skimr` and keep improving the package. I think there will be more progress in the future versions of `skim`. And now there are some new things I like and some that make the output of `skim()` less attractive. There are my thoughts.

# Part A

The output of the current version of `skimr` v2:

![image](https://user-images.githubusercontent.com/12725868/53091738-6bc56b00-351b-11e9-868c-96a4182b23a1.png)
**Fig. 1**

Numbers in the plot:
- 1 It is an excellent decision, as to use "Data summary" instead of "Skim summary";
`Number of rows` and `Number of columns` instead of `n obs` and `n variables` also makes the output more understandable for less-technical users.
- 2 Why are backticks needed here?
- 2 Is the word "Values" needed at all?
- 3, 6 and 7 It would be easier to understand the output if these places contained blank lines.
- 4, 5 it was easier to understand the output if:
     - there was a colon after "Column type frequency",
     - type names were indented, 
     - column type frequencies were not so far from the column type names;
     - and there were blank lines above and below this section, e.g.:
```
Number of rows:    150
Number of columns:   5

Column type frequency:      
  factor:       1
  numeric:      4

Group variables:   None
```

The output would take more rows with additional blank lines, but it would be less tiring to understand the main parts of the output.

Is there a good reason why all the numbers are right-aligned to the dataset's name?
In some situations, it is not easy to understand, which number belongs to which name:

![image](https://user-images.githubusercontent.com/12725868/53094221-383a0f00-3522-11e9-9371-aa030c74543a.png)
**Fig. 2**

Could you use left alignment here?

**To summarize:** I like new less technical words like `Data summary` and would like them in the future version of `skim`, but I think that alignment and spacing of the outout should be improved as now more effort is needed to understand output correnctly.
Some good features that existed in the previous versions of `skim` (e. g., v1) were removed.

# Part B

Next, in RStudio Notebooks, the result of `skim()` consists of 2 separate outputs:
![image](https://user-images.githubusercontent.com/12725868/53092916-a977c300-351e-11e9-9966-884c37c3f0fc.png)
**Fig. 3**

![image](https://user-images.githubusercontent.com/12725868/53092934-b3012b00-351e-11e9-97fb-6ec1c3a7d664.png)
**Fig. 4**

Is it expected to have separate outputs? If yes, maybe it's better to use two separate functions: **Fig. 4** may be produced by `summary(skim(data))`  and **Fig. 3**  by `skim(data)`. What are your thoughts on this?

# Part C

It seems that `knitr::kable()` (and `pander::pander()`) does not work as expected yet:

![image](https://user-images.githubusercontent.com/12725868/53093303-b77a1380-351f-11e9-9764-1125a149728f.png)
**Fig. 5**

![image](https://user-images.githubusercontent.com/12725868/53093429-12136f80-3520-11e9-8afc-7706ef040008.png)
**Fig. 6**

**Comment by elinw** [comment]
We have a separate summary method, summary is a generic, just like you can do summary.lm or summary.numeric, so now it is the same whether you use it on its own or you opt to have it displayed as part of it's output.  What is new is that now it is a data frame instead of concatenated strings.
Values is the name of the variable storing the results.  I believe actually for screen readers it is very important to have titles of any table columns.  That is, it will make accessible html or text in a Word document or results in the console, though I don't know much about how visually impaired people use the console.

@michaelquinn32 and I were also talking about potentially using a line under the Data summary line.
I do want to have indenting but it's actually more tricky than you might think to make it work in all contets.

Overall these are good thoughts that I'll look at and give you feedback on as we move along.

**Comment by elinw** [comment]
@GegznaV @michaelquinn32 https://github.com/ropensci/skimr/pull/412 implements a number of these suggestions. Please take a look and see what you think,

**Comment by GegznaV** [comment]
Skim summary looks better:

![image](https://user-images.githubusercontent.com/12725868/53495393-90d05580-3aa8-11e9-9f9b-1405461a8a89.png)

**Comment by michaelquinn32** [comment]
For very long names, would it be reasonable to support a max  char for names? If we set it at 15, then names in the table would take a max of 13 characters.

`really_long_na...`

**Comment by elinw** [comment]
That's basically what I had in my branch, which I merged yesterday.

I'm going to close this since I merged a lot of fixes .. let's open new issues for additional improvements/ ideas.
