### ISSUE TITLE
Error in FUN(X[[i]], ...) :    object '_dplyr_quo_is_variable_reference' not found

### ISSUE THREAD

**Issue by sfirke** [ropensci/skimr#409]
When I run `mtcars %>% skim(cyl)` I get:

```
Skim summary statistics
 n obs: 32 
 n variables: 11 
Error in FUN(X[[i]], ...) : 
  object '_dplyr_quo_is_variable_reference' not found
```

Here's my session info:
<details>
<summary>─ Session info </summary> ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2019-02-21                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date       source                          
 assertthat    0.2.0      2017-04-11 CRAN (R 3.5.0)                  
 clisymbols    1.2.0      2017-05-21 CRAN (R 3.5.0)                  
 crayon        1.3.4      2017-09-16 CRAN (R 3.5.0)                  
 dplyr       * 0.8.0.9000 2019-02-20 Github (tidyverse/dplyr@22b923e)
 glue          1.3.0      2018-07-17 CRAN (R 3.5.1)                  
 magrittr      1.5        2014-11-22 CRAN (R 3.5.0)                  
 pillar        1.3.1      2018-12-15 CRAN (R 3.5.2)                  
 pkgconfig     2.0.2      2018-08-16 CRAN (R 3.5.1)                  
 purrr         0.3.0      2019-01-27 CRAN (R 3.5.0)                  
 R6            2.3.0      2018-10-04 CRAN (R 3.5.2)                  
 Rcpp          1.0.0      2018-11-07 CRAN (R 3.5.1)                  
 rlang         0.3.1      2019-01-08 CRAN (R 3.5.2)                  
 rstudioapi    0.7        2017-09-07 CRAN (R 3.5.0)                  
 sessioninfo   1.0.0      2017-06-21 CRAN (R 3.5.1)                  
 skimr       * 1.0.4      2019-01-13 CRAN (R 3.5.2)                  
 tibble        2.0.1      2019-01-12 CRAN (R 3.5.2)                  
 tidyselect    0.2.5      2018-10-11 CRAN (R 3.5.2)                  
 withr         2.1.2      2018-03-15 CRAN (R 3.5.0)                  
 yaml          2.2.0      2018-07-25 CRAN (R 3.5.1)   
</details>

**Comment by elinw** [comment]
Can you try the develop branch? I just merged some tidyverse related changes.  Also can you update your dplyr?

**Comment by elinw** [comment]
According to this issue https://github.com/tidyverse/dplyr/issues/3796  you may need to reinstall dplyr in a new r session with no other sessions running.  I am still looking to see if I can reproduce the issue.

**Comment by elinw** [comment]
@sfirke Hi ... did this get solved?

**Comment by sfirke** [comment]
Yes thanks for the advice above, I tried those steps and this is resolved.  I installed the latest version of dplyr from CRAN, then the latest skimr from GitHub, and it works as expected.  Thanks @elinw !
