### ISSUE TITLE
skim returns Inf for all-NA character vectors

### ISSUE THREAD

**Issue by svraka** [ropensci/skimr#414]
A similar issue has been discussed extensively (see #221, #224, #290) and fixed in #237 for numeric columns but all-NA character columns still result in warnings:

``` r
library(skimr)

tibble:::tibble(v = rep(NA_character_, 10)) %>% skim
#> Warning in min(characters, na.rm = TRUE): no non-missing arguments to min;
#> returning Inf
#> Warning in max(characters, na.rm = TRUE): no non-missing arguments to max;
#> returning -Inf
#> Skim summary statistics
#>  n obs: 10 
#>  n variables: 1 
#> 
#> -- Variable type:character --------------------------------------------------
#>  variable missing complete  n min  max empty n_unique
#>         v      10        0 10 Inf -Inf     0        0
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

As far as I understand, the recent change to `allowNA = TRUE` in d274a11f4f0b236b0428229acb9008152db88503 doesn't solve this issue and there no tests for all-NA vectors either.

Besides that skimr shouldn't throw warnings, to my eyes NAs make sense than `Inf`/`-Inf` for minimum and maximum character lengths if all values are NA. I'd be happy to put together a small PR in the coming days.

**Comment by elinw** [comment]
So you think it should return NA when all NA? That seems reasonable and consistent to me   I'd be happy to take a pull request for that.  Please make sure to add it to news.md and also add yourself as a contributor.

**Comment by elinw** [comment]
https://github.com/ropensci/skimr/pull/418  PR ... I suppose there could be a discussion about whether n_unique should also return NA (or 1?)  rather than 0.  However I think in the context of skimming a data set the row of results gives you the all NA message.

**Comment by elinw** [comment]
Since this seems non controversial, if I don't hear from anyone I'm going to merge  PR #418  later today. @michaelquinn32  @svraka
