### ISSUE TITLE
skim_with() fails to change the defaults if integers are present

### ISSUE THREAD

**Issue by GegznaV** [ropensci/skimr#427]
I use `skimr` v2 (installed it today). `skim_with()` fails to use non-default summary functions (or remove the default ones), if **integers** are present in a dataset.

E.g., `hist` is not removed:

![image](https://user-images.githubusercontent.com/12725868/55036221-a3479b80-5022-11e9-838d-0f3cf8d8a847.png)

It seems that function always uses the defaults:

![image](https://user-images.githubusercontent.com/12725868/55036326-f4578f80-5022-11e9-9a99-6e2dacd66245.png)

The code:

```r
library(skimr)
data("faithful")

faithful$eruptions <- as.integer(faithful$eruptions)
dplyr::glimpse(faithful)

my_skim <- skim_with(numeric = sfl(hist = NULL))
my_skim(faithful)

my_skim <- skim_with(numeric = sfl(iqr = IQR, p25 = NULL, p75 = NULL))
my_skim(faithful)
```

I think, after the issue is solved, an appropriate unit test should be added.

**Comment by elinw** [comment]
Okay so I don't think that the issue is integers specifically, but is the situation where two classes are being pushed together into the same subtable.   @michaelquinn32  The other idea would be the issue of how we're  finding which statistics apply to which group.  v 

Thanks for doing so much testing!

**Comment by elinw** [comment]
@GegznaV I tried your code and @michaelquinn32's branch (now in v2) works for me, do you want to do your testing?  Again thanks for really pushing on finding edge cases for us.

**Comment by GegznaV** [comment]
Works as expected now.
