### ISSUE TITLE
Add empty lines between summaries of different variable types

### ISSUE THREAD

**Issue by GegznaV** [ropensci/skimr#428]
To make the output of `skim()` (v2) more readable, empty lines before summaries of different types of variables are needed. E.g., before the `-- Variable type: numeric ------` in the example (see red line):

![image](https://user-images.githubusercontent.com/12725868/55036766-4947d580-5024-11e9-8ef2-ea7d914a3c6b.png)

**Comment by elinw** [comment]
Okay look at this
https://github.com/ropensci/skimr/pull/429

**Comment by GegznaV** [comment]
Works nice:

![image](https://user-images.githubusercontent.com/12725868/55073144-a0d25980-5095-11e9-8ce3-05f630b11ff0.png)

**Comment by elinw** [comment]
Great!
