### ISSUE TITLE
Report only selected statistics?

### ISSUE THREAD

**Issue by briatte** [ropensci/skimr#452]
Apologies if this is obvious, but I could not find an issue or hint in the README:

Is there a way to tell `skim` to report everything it does by default, *except* for a set of statistics (`p25` and `p75`, for instance)?

Context -- in Rstudio, the default `skim` output is just a bit too large for my console window.

**Comment by elinw** [comment]
Yes, you can use either p25=NULL  or the tidy select functions.

**Comment by briatte** [comment]
Thanks!
