### ISSUE TITLE
knitted output of skimr() summary() function looks strange 

### ISSUE THREAD

**Issue by GegznaV** [ropensci/skimr#453]
I wrote `skimr::skim(faithful)` and knitted in a bookdown project.
The top part of the summary is strange:

![image](https://user-images.githubusercontent.com/12725868/57935217-fbd04200-78c9-11e9-85b7-920bfb42a9bb.png)

skimr v2

**Comment by elinw** [comment]
Interesting ... I hadn't tried skimr in bookdown recently. we may need to go back to hard coding two blanks at the ends of lines.   Could you possibly inspect the html  for that block and paste it here?

**Comment by GegznaV** [comment]
The issue is not Bookdown specific. It occurs in R Markdown.
Here are the files (Rmd and html):
[skimr__skim_faithful.zip](https://github.com/ropensci/skimr/files/3193869/skimr__skim_faithful.zip)

Do you know, how to suppress this kind of output and get the output which is the same as in R console?
R chunk options `results='markup'`, `results='asis'`, and `paged.print=FALSE` do not have any effect. (`paged.print=FALSE` has effect in R Notebooks). I. e., there should be an easy way to disable "auto as-is" printing. Otherwise it is frustrating to use skim in knitted documents.

HTML code:

```
<table style="width:49%;">
<caption>Data summary</caption>
<colgroup>
<col width="34%"></col>
<col width="13%"></col>
</colgroup>
<tbody>
<tr class="odd">
<td align="left">Name Number of rows Number of columns</td>
<td align="left">faithful 272 2</td>
</tr>
<tr class="even">
<td align="left">Column type frequency: numeric</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">missing</th>
<th align="right">complete</th>
<th align="right">n</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">eruptions</td>
<td align="right">0</td>
<td align="right">272</td>
<td align="right">272</td>
<td align="right">3.49</td>
<td align="right">1.14</td>
<td align="right">1.6</td>
<td align="right">2.16</td>
<td align="right">4</td>
<td align="right">4.45</td>
<td align="right">5.1</td>
<td align="left">▇▂▂▇▇</td>
</tr>
<tr class="even">
<td align="left">waiting</td>
<td align="right">0</td>
<td align="right">272</td>
<td align="right">272</td>
<td align="right">70.90</td>
<td align="right">13.59</td>
<td align="right">43.0</td>
<td align="right">58.00</td>
<td align="right">76</td>
<td align="right">82.00</td>
<td align="right">96.0</td>
<td align="left">▃▃▂▇▂</td>
</tr>
</tbody>
</table>
 
```

**Comment by elinw** [comment]
So it looks like we need to make sure that the first rows get properly divided into `<td></td>` cells and possibly even `<th></th>`

**Comment by GegznaV** [comment]
If there is an intermediate Markdown code for tables, it may indicate incorrect formatting. Something like this where the end of column 1 is indicated incorrectly:
```md
Header of line 1  Header of line 2
-------------- -----------------------
contents 1           contents 2
contents 1           contents 2
```

**Comment by elinw** [comment]
Right, I think that one of the big inconsistencies in markdown flavors is how tables are marked up.  So I bet pandoc is expecting something that is different than what rmarkdown is generating.

**Comment by elinw** [comment]
Okay I pushed a fix for this that breaks grouped data but it is in markdown_to_pdf branch.  Once I find out why the grouped data isn't working I'll make a PR.  But in the meantime feel free to test.  It required changing the blank lines that we had added to  solid lines, I don't love this, maybe that's something that can be solved also but for now at least all the data are in the correct rows.

**Comment by elinw** [comment]
https://github.com/ropensci/skimr/pull/466   So now it works with group.  I had to replace our lovely blank spaces with horizontal lines.  It could be that we do that condtionally when knitting, but for now this works. @GegznaV  @michaelquinn32

**Comment by GegznaV** [comment]
Now it looks much better.
Just two notes:

1) The summary table is not centered anymore. 
2) Those lines (see red arrows), I'm not sure if they are necessary as they consume two extra lines and table gets bigger. I'm not sure if they should be removed too as they give clarity.



![image](https://user-images.githubusercontent.com/12725868/59914898-172bf100-9424-11e9-9d85-226c0da952f7.png)

Is there an option to have a summary of variables only (without the part, that can be extracted with `summary(skim(...))`)? I.e., just this part (for all types of variables, if there are several):

![image](https://user-images.githubusercontent.com/12725868/59915004-50fcf780-9424-11e9-87d8-785c9ba4923c.png)

**Comment by elinw** [comment]
I'm really of mixed minds about the lines because I do feel we added them for a good reason in the prevsious version, there a clearly separate sections.  But they do take up a lot of space and are kind of a pain to produce. 
 There's a parameter setting that says to print with no summary.

**Comment by elinw** [comment]
Okay I merged this into V2 as it is, we can always discuss it more. At least now it works better.
I'm surprised about how many issues we are getting about bookdown so it does seem like we should try to look at the handling there more.

**Comment by elinw** [comment]
See #473 where I am putting all bookdown issues for now.
