### ISSUE TITLE
Format line length

### ISSUE THREAD

**Issue by alexhallam** [ropensci/skimr#480]
I am printing the output of a skim. One annoyance is the length of the lines that separate the variable types. Can the length of these lines be formatted?

Here is an example. I think you will see that the output file would look cleaner if the line length was shorter.

```r
library(skimr)
skimr::skim(airquality) %>%
 skimr::kable() %>%
 capture.output %>%
 cat(file="output.txt", sep = "\n")
```

**Comment by elinw** [comment]
Have you tried  the v2 branch?

**Comment by alexhallam** [comment]
I will give that a try.
