### ISSUE TITLE
using skim_tee with functions

### ISSUE THREAD

**Issue by randomgambit** [ropensci/skimr#482]
Hello there,

I think the `skim_tee` is really a super powerful function that allows me to create summary stats in a middle of a `magrittr` pipe.

However, I was not able to make it work in a very common situation. Consider this example

```
tibble(myval = c(1,1,1,2,3,3,3),
       group = c('a','a','a','a','a','b','b')) %>% 
  filter(group == 'a') %>% 
  skim_tee(unique(.$myval))
Error in inds_combine(.vars, ind_list) : Position must be between 0 and n
```

Here I am simply trying to print some summary stats about the **unique values** of a column. I cannot get this to work with alternatives such as `dplyr::distinct(myval)) or base unique(myval).

Is this a bug? Is this a limitation of skimr?

Thanks!

**Comment by elinw** [comment]
So I'm a little confused about what you are doing ... you can't skim(unique(.$myval)) either.  However

```
tibble(myval = c(1,1,1,2,3,3,3),
       group = c('a','a','a','a','a','b','b')) %>% 
    filter(group == 'a') %>% select(myval) %>%
    distinct() %>% skim_tee()

```  
gets what you want, I think.   Is that right?

**Comment by randomgambit** [comment]
Hi @elinw yes what you do works, but the problem is having the summary stats of the unique values while keeping the original values in the `pipe`. In other words, in my `dplyr` chain I need to keep all the values of `myval` (not only the unique ones). Hence I was trying to call `unique()` within `skim_tee`.

Do you see my point?
Thanks!

**Comment by michaelquinn32** [comment]
Hi Olaf!

`skim_tee()` returns exactly the same data that it's passed. If you manipulate the data within the function call, you can only get the manipulated data back.

There's a pipe for doing T-style operations, you can combine it with `skim_tee` to get the side effect that you want.
https://magrittr.tidyverse.org/reference/tee.html

``` r
library(tibble)
library(magrittr)
library(dplyr)
#>
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#>
#>     filter, lag
#> The following objects are masked from 'package:base':
#>
#>     intersect, setdiff, setequal, union
library(skimr)

tibble(
  myval = c(1,1,1,2,3,3,3),
  group = c('a','a','a','a','a','b','b')
) %T>% {
    filter(., group == 'a') %>%
    select(myval) %>%
    distinct() %>%
    skim_tee()
}

#> ── Data Summary ────────────────────────
#>                         Value
#> Name                    .data
#> Number of rows              3
#> Number of columns           1
#>
#> Column type frequency:
#>   numeric                   1
#>
#> Group variables          None
#>
#> ── Variable type: numeric ─────────────────────────────────────────────────
#>   skim_variable n_missing complete_rate  mean    sd    p0   p25   p50   p75
#> 1 myval                 0             1     2     1     1   1.5     2   2.5
#>    p100 hist
#> 1     3 ▇▁▇▁▇
#> # A tibble: 7 x 2
#>   myval group
#>   <dbl> <chr>
#> 1     1 a
#> 2     1 a
#> 3     1 a
#> 4     2 a
#> 5     3 a
#> 6     3 b
#> 7     3 b
```

**Comment by randomgambit** [comment]
haha wonderful! thanks!
