### ISSUE TITLE
Split wide cells with line breaks

### ISSUE THREAD

**Issue by vrodriguezf** [ropensci/skimr#483]
Hi,

The column names of my data frame are long, and then, when I print the result of `skim(dataframe)`, I cannot see all the information of each variable in a single row, which is much more descriptive. It looks like this:

![image](https://user-images.githubusercontent.com/7083752/65141090-354bc200-da10-11e9-8070-d6b98e50c8fd.png)

Is there anything that I can do in order to splite wide cells into multiple lines? I am working in Jupyter notebook.

Best!

**Comment by michaelquinn32** [comment]
Although likely the least impactful long-term fix, one thing you can do within a notebook is set `options(width = 180)` or some other large number.

R's default option is meant for working on small terminals, and modern monitors with big web browser windows have a lot of more real estate to play around in.
https://stat.ethz.ch/R-manual/R-devel/library/base/html/options.html

The upcoming version of skimr (which I swear will eventually be released) uses pillar for printing, which supports some additional long name trimming:
https://github.com/r-lib/pillar

**Comment by vrodriguezf** [comment]
Awesome reply, thank you so much!
