### ISSUE TITLE
Error loading after fresh CRAN install

### ISSUE THREAD

**Issue by jzadra** [ropensci/skimr#488]
```
> install.packages("skimr")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/skimr_1.0.7.tgz'
Content type 'application/x-gzip' length 781259 bytes (762 KB)
==================================================
downloaded 762 KB


The downloaded binary packages are in
	/var/folders/5_/l71sk6kn29z17n011g8kld5m0000gp/T//RtmpoCevMf/downloaded_packages
> require(skimr)
Loading required package: skimr
Error: package or namespace load failed for ‘skimr’:
 .onLoad failed in loadNamespace() for 'skimr', details:
  call: NULL
  error: Internal error: Expected call in `quo_invert()`
```

**Comment by michaelquinn32** [comment]
Eek! That's no good.

Can you please call `sessionInfo()` and print the results here? Thanks!

**Comment by elinw** [comment]
https://github.com/tidyverse/purrr/blob/master/R/utils.R#L256 ?

**Comment by elinw** [comment]
@michaelquinn32  maybe we need higher minimum versions?

**Comment by courtiol** [comment]
I can reproduce the bug with latest `{purrr}` and `{rlang}`:

```{r}
> install.packages('skimr')
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/skimr_1.0.7.tgz'
Content type 'application/x-gzip' length 781259 bytes (762 KB)
==================================================
downloaded 762 KB
The downloaded binary packages are in
	/var/folders/r4/nmf9vqyj7pz968sk2vrtmbvm0000gn/T//RtmpjMc6Wp/downloaded_packages
> library(skimr)
Error: package or namespace load failed for ‘skimr’:
 .onLoad failed in loadNamespace() for 'skimr', details:
  call: NULL
  error: Internal error: Expected call in `quo_invert()`
> packageVersion('skimr')
[1] ‘1.0.7’
> packageVersion('purrr')
[1] ‘0.3.2’
> packageVersion('rlang')
[1] ‘0.4.0.9005’
```

But with `{skimr}` version 2 (and the rest as is), it all works like a charm:

```{r}
> devtools::install_github("ropensci/skimr", ref = "v2")
Downloading GitHub repo ropensci/skimr@v2
✔  checking for file ‘/private/var/folders/r4/nmf9vqyj7pz968sk2vrtmbvm0000gn/T/RtmpjMc6Wp/remotesd1a85fad9141/ropensci-skimr-58b9e30/DESCRIPTION’ ...
─  preparing ‘skimr’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘skimr_2.0.tar.gz’
   
* installing *source* package ‘skimr’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (skimr)
> library(skimr)
> packageVersion('skimr')
[1] ‘2.0’
```
So while it does not explain the issue, a simple work around is to use the 'new' skimr.
++

**Comment by jzadra** [comment]
> https://github.com/tidyverse/purrr/blob/master/R/utils.R#L256 ?
> 
> [r-lib/ymlthis#36](https://github.com/r-lib/ymlthis/issues/36)
> @jzarda
> Can you try updating rlang and purrr?

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testthat_2.2.0 devtools_2.1.0 usethis_1.5.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2        rstudioapi_0.10   magrittr_1.5      tidyselect_0.2.5  pkgload_1.0.2    
 [6] R6_2.4.0          rlang_0.4.0.9004  dplyr_0.8.3       tools_3.6.0       pkgbuild_1.0.5   
[11] packrat_0.5.0     sessioninfo_1.1.1 cli_1.1.0         withr_2.1.2       remotes_2.1.0    
[16] assertthat_0.2.1  digest_0.6.21     rprojroot_1.3-2   tibble_2.1.3      crayon_1.3.4     
[21] processx_3.4.1    purrr_0.3.2       callr_3.3.2       fs_1.3.1          ps_1.3.0         
[26] memoise_1.1.0     glue_1.3.1        pillar_1.4.2      compiler_3.6.0    desc_1.2.0       
[31] backports_1.1.5   prettyunits_1.0.2 pkgconfig_2.0.3

**Comment by elinw** [comment]
Well this is not a happy thing.

**Comment by elinw** [comment]
I just did fresh installs and I have rlang version of 0.4.0  but you are showing 0.4.0.9004  and  0.4.0.9005 ... did you possibly install the development version?  Would you be willing to try updating to the current development version?

**Comment by elinw** [comment]
Yes, can you please update to what is in github now because I believe they fixed the problem.  Or try installing the CRAN version because I don't think it ever had this problem.
