### ISSUE TITLE
Re-implement `to_long` as a generic

### ISSUE THREAD

**Issue by michaelquinn32** [ropensci/skimr#559]
The `to_long` function currently does two things:

* `skim()` a data frame
* coerce the skimmed data frame to the old format

This behavior should happen over two functions. The first works with data frame like objects, the second with `skim_df` objects. We should have a generic for dealing with the different methods, and you should be able to pass a skim function as an argument.

#558 by @sethlatimer addresses the issues with arguments and conditional logic. This proposes a more idiomatic solution.

**Comment by elinw** [comment]
This fits with the way we have in general been thinking about what happens to skim objects, the current `to_long()` is kind of a hack and it would potentially be good to look at it more carefully anyway. Also would we just consider it a data frame/tibble or would it be a distinct type of object? `to_long()` was written before we really came to a final idea about the characteristics of a `skim_df` object.
