### ISSUE TITLE
error in package installation

### ISSUE THREAD

**Issue by NoushinN** [ropensci/skimr#571]
Are there package dependencies with `repr`?
This is my error:    
    `Error:    package or namespace load failed for ‘skimr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘repr’
`

**Comment by michaelquinn32** [comment]
Hi Noushin!

Yes. `repr` is a dependency. We use it for skim out in notebooks.

Best wishes,
Michael

**Comment by NoushinN** [comment]
Thank you @michaelquinn32 , however it seems like `repr` is under development? not able to install [`repr` ](https://github.com/IRkernel/repr/)

**Comment by michaelquinn32** [comment]
repr is a CRAN package: https://cran.r-project.org/web/packages/repr/index.html

How are you trying to install it?

**Comment by elinw** [comment]
@NoushinN  were you able to get it updated or installed?

**Comment by NoushinN** [comment]
@elinw thank you for asking, I am upgrading my R to 3.6.2..sorry this has taken a while, I needed more administrative permissions to do this..will update you

**Comment by NoushinN** [comment]
@elinw @michaelquinn32 works great with the new R version 3.6.2, thank you both very much!
