### ISSUE TITLE
Improve performance by adding support for futures

### ISSUE THREAD

**Issue by michaelquinn32** [ropensci/skimr#579]
We can take advantage of the API from `furrr`, https://github.com/DavisVaughan/furrr, which opens up a lot of different tools to speed up skim time.

By default, nothing changes. But by using a computation strategy from the `future` package, there should be an opportunity for a nice speed up. Here's some examples:
https://github.com/HenrikBengtsson/future

**Comment by elinw** [comment]
That looks great. What do we need to do?

**Comment by michaelquinn32** [comment]
After playing around a bit with this, I don't think this is the right solution. I wasn't seeing the performance gains that I hoped for. In fact, switching to a multiprocessing was slower for the cases that I tried.

But I did a little profiling and found that is.data.frame can be a little expensive on bigger, lazy-loaded datasets. `inherits()` is better. I'll push that.
