### ISSUE TITLE
n_whitespace not count correctly?

### ISSUE THREAD

**Issue by DavZim** [ropensci/skimr#588]
Not really sure if this is intended behavior or if I misunderstand the documentation:

The documentation of `?get_skimmers()`/`?stats()` for character-vectors, refers to the returning value of `n_whitespace` as "Calculate the number of rows containing only whitespace values using s+ regex.".
The code however does not check for _only_ whitespace but for multiple starting whitespaces.

I.e., in the following code, I would expect to get 1 `whitespace`, but got 2.

``` r
df <- data.frame(x = c("not empty", "  not empty", "    "), stringsAsFactors = FALSE)
df
#>             x
#> 1   not empty
#> 2   not empty
#> 3
str(df)
#> 'data.frame':    3 obs. of  1 variable:
#>  $ x: chr  "not empty" "  not empty" "    "

# expected 1 whitespace, got 2 whitespace
print(skimr::skim(df))
#> ── Data Summary ────────────────────────
#>                            Values
#> Name                       df    
#> Number of rows             3     
#> Number of columns          1     
#> _______________________          
#> Column type frequency:           
#>   character                1     
#> ________________________         
#> Group variables            None  
#> 
#> ── Variable type: character ────────────────────────────────────────────────────
#>   skim_variable n_missing complete_rate   min   max empty n_unique whitespace
#> 1 x                     0             1     4    11     0        3          2
```

<sup>Created on 2020-05-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
To my understanding, the correct version would be to change `"^\\s+"` to `^\\s+$` in [`stats.R` line 41](https://github.com/ropensci/skimr/blob/daba7e8f8f5256b3987ac7d211a6ab1478b553d4/R/stats.R#L41).

Also and not relating to this issue: Great work, I love the package and find it really helpful!

**Comment by elinw** [comment]
Thanks! Yes that is supposed to count rows that are "only white space" not that "start with white space" ... do you want to send a pull request for that?  We should add a test too.
