### ISSUE TITLE
Duration S4 in lubridate

### ISSUE THREAD

**Issue by rubenarslan** [ropensci/skimr#592]
Hi, the S4 Duration class seems to confuse skimr. It skims it using the default numeric skimmer—even though that leads to an error, because Duration and double vctrs can't be combined and even if a custom numeric skimmer is implemented. 

``` r
x <- tibble::tibble(x = lubridate::duration(1), y = 1)
skimr::skim(x)
#> Error: Problem with `summarise()` input `skimmed`.
#> x Can't combine `..1$numeric.p0` <Duration> and `..2$numeric.p0` <double>.
#> ℹ Input `skimmed` is `purrr::map2(...)`.
#> ℹ The error occured in group 1: skim_type = "numeric".
x <- tibble::tibble(x = lubridate::duration(1))
skimr::skim_with(
  numeric = skimr::sfl(
    mean = skimr::get_one_default_skimmer("numeric")$mean,
    sd = skimr::get_one_default_skimmer("numeric")$sd,
    min = skimr::get_one_default_skimmer("numeric")$p0,
    median = skimr::get_one_default_skimmer("numeric")$p50,
    max = skimr::get_one_default_skimmer("numeric")$p100,
    hist = skimr::get_one_default_skimmer("numeric")$hist
  ),
  append = FALSE
)(x)
```

<table>
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">x</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>

**Variable type: numeric**

<table>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">x</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1s</td>
<td style="text-align: right;">1s</td>
<td style="text-align: right;">1s</td>
<td style="text-align: right;">1s</td>
<td style="text-align: right;">1s</td>
<td style="text-align: left;">▁▁▇▁▁</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by elinw** [comment]
Very interesting, thanks for this report.  Looking at the traceback it seems like it is hitting the histogram and failing, but I'll look further.

Elin

**Comment by elinw** [comment]
I looked for that error message and it seems to come up in a number of places related to either pillar or tibble. I'm not sure actually why it is trying to process Duration objects as numeric rather than falling back to character and I can see why trying to do so would create problems since I am pretty sure Duration will have different methods.

**Comment by elinw** [comment]
Interestingly this seems to work

```
x <- tibble::tibble(x = lubridate::duration(1))
skimr::skim_with(
  Duration = skimr::sfl(
    mean = skimr::get_one_default_skimmer("numeric")$mean,
    sd = skimr::get_one_default_skimmer("numeric")$sd,
    min = skimr::get_one_default_skimmer("numeric")$p0,
    median = skimr::get_one_default_skimmer("numeric")$p50,
    max = skimr::get_one_default_skimmer("numeric")$p100# ,
    #hist = skimr::get_one_default_skimmer("numeric")$hist
  ),
  append = FALSE
)(x)
```
The question in that case would be why is it treating this as numeric.

**Comment by rubenarslan** [comment]
No, as far as I understand the bug, it's not about the histogram, but because in the summary Duration p0s etc. are grouped with numeric p0s, but they have different classes and vctrs 0.3.0 won't coerce them automatically.

From this standpoint, it's not surprising that defining an explicit handler for Durations helps—they get grouped in a new tibble now, so no binding of rows across types. What surprised me is that skimr doesn't fail/complain—like it does with `haven_labelled` when a skimr for a class is not defined. Maybe because duration is S4 and `haven_labelled` S3? Or because `haven_labelled`has explicit classes including vctrs_vctr and integer now: 

> class(haven::labelled(1:10))
[1] "haven_labelled" "vctrs_vctr"     "integer" 

Don't know enough about S4/S3 though.

**Comment by elinw** [comment]
Yes, haven_labelled works the way I would expect this to work, that's why I have it in skimrExtra https://github.com/elinw/skimrExtra. 
 https://github.com/elinw/skimrextra/blob/master/R/get_skimmers.R#L46

So if I do
```
inline_hist(x$x)
```
>Error: Incompatible duration classes (Duration, numeric). Please coerce with `as.duration`.

So the histograms also produce the issue but this is separate from the way skimr itself is causing problems. That's why 
```
mean(x$x)
```
> 1

But if you try to skim it with just  `mean()`  it doesn't work.

So I think you are probably right that it is something about S4 classes that may be causing this.

http://adv-r.had.co.nz/S4.html

I think that because Duration as an S4 class _inherits_ from numeric that is different than an S3 class where and we are going to have to really look at how S4 dispatch is going to work in skimr.  @michaelquinn32

**Comment by elinw** [comment]
```
showMethods("as.duration")
```
Function: as.duration (package lubridate)
>x="ANY"
>x="character"
>x="difftime"
>x="Duration"
>x="Interval"
>x="logical"
>x="numeric"
>x="Period"

So .... 
```
a <- lubridate::duration(1)
a <- as.difftime(a)

x <- tibble::tibble(a = as.difftime(a), y = 1)
skim(x)
```
 Works fine because we have a skimmer for difftime.  But the problem is that S4 is going in the other direction and using numeric rather than either finding the difftime skimmers or falling back to character.

**Comment by elinw** [comment]
So solving this specifically for Duration or possibly Timespan (which Duration inherits from)

```
get_skimmers.Timespan <- function(column) {
   modify_default_skimmers("difftime", new_skim_type = "Timpespan")
 }
```
or
```
get_skimmers.Duration <- function(column) {
   modify_default_skimmers("difftime", new_skim_type = "Duration")
 }
```
Using Timespan will also catch Interval and Period objects.
