### ISSUE TITLE
Warning message: package ‘skimr’ is not available (for R version 3.3.2) 

### ISSUE THREAD

**Issue by kasa10** [ropensci/skimr#595]
> install.packages("skimr")
Installing package into ‘C:/Users/..../win-library/3.3’
(as ‘lib’ is unspecified)
Warning message:
package ‘skimr’ is not available (for R version 3.3.2) 

how to fix it?
In Visual studio

**Comment by kasa10** [comment]
Installing skimr
"C:/..../R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/..../devtools750336d6a6d/ropensci-skimr-b8be860"  \
  --library="C:/Users/..../R/win-library/3.3" --install-tests 

ERROR: dependencies 'cli', 'rlang', 'tidyselect', 'vctrs' are not available for package 'skimr'
* removing 'C:/Users/kiril/OneDrive/Документы/R/win-library/3.3/skimr'
Error: Command failed (1)

**Comment by elinw** [comment]
That's frustrating ... I'm thinking that some of the dependencies now have a higher minimum version of R.

**Comment by elinw** [comment]
By the way did you install those dependencies? 'cli', 'rlang', 'tidyselect', 'vctrs'

**Comment by kasa10** [comment]
> By the way did you install those dependencies? 'cli', 'rlang', 'tidyselect', 'vctrs'

With visual studio did not work, installed Rstudio everything is normal
