### ISSUE TITLE
Predicates are not supported

### ISSUE THREAD

**Issue by brodz** [ropensci/skimr#611]
Hi,

I tried to use `where(is.numeric)` to select all numeric columns. This produces the following error message:

> Error: This tidyselect interface doesn't support predicates yet.
ℹ Contact the package author and suggest using `eval_select()`.

Would it be sufficient to change `vars_select` to `eval_select`in [skim_with.R](https://github.com/ropensci/skimr/blob/461f9a5a3e768d999df43f284f60dd4a707c6753/R/skim_with.R#L97)?

**Comment by michaelquinn32** [comment]
Thanks for pointing that out!

That seems to be the root issue: we need to update the tidyselect API that we use. It's not exactly a one-to-one replacement, as we also need to follow some rlang semantics (capturing expressions, etc.).

https://tidyselect.r-lib.org/articles/syntax.html
