### ISSUE TITLE
Improve nested usage by allowing "data_name" to be overridden as an arg.

### ISSUE THREAD

**Issue by jw5** [ropensci/skimr#614]
With a small backward compatible change it would be possible to invoke skim from within other functions and pass the original variable name from a caller higher up the call stack rather than using the temporary name internal to the calling function.

For example

```
myFunc <- function(x) skim(x)

myFunct(myData)
```
Shows the name of myData as "x", rather than the more desirable "myData".

However, a small change to the current code:
```
skim <- function (data, ...) 
{
    data_name <- rlang::expr_label(substitute(data))
    if (!inherits(data, "data.frame")) {
        data <- as.data.frame(data)
    }
...
```

could be changed to this:

```
skim <- function (data, data_name = rlang::expr_label(substitute(data)), ...) 
{
    if (!inherits(data, "data.frame")) {
        data <- as.data.frame(data)
    }
...
```

would allow
```
myFunc <- function(x) skim(x, data_name = deparse(substitute(x)))

myFunct(myData)
```
To display the original variable name "myData" in the skim output.

Thanks,
Jim

**Comment by elinw** [comment]
That's very nice! @michaelquinn32 do you agree?

**Comment by michaelquinn32** [comment]
This works for me! Would you mind opening a pull request so that we can merge this into the code?

**Comment by elinw** [comment]
I am going to mention that the reason we do that currently is so we can display the data name in the print by making it an attribute`df_name`  .  We could also create a convenience function to return that.

**Comment by elinw** [comment]
@jw5 If you would send us a PR, please also add yourself as a contributor in the description file.

**Comment by elinw** [comment]
@jw5 @michaelquinn32  I think it would make sense to get this into the next release, do you agree?

**Comment by michaelquinn32** [comment]
I agree. This is a great addition. Thanks!

**Comment by elinw** [comment]
Interestingly it also has the benefit of removing the ``  (backticks)  around  the data set name.

It looks to me as though this breaks tidy select.  I'll push up a branch with failing tests after I look at it some more.
