### ISSUE TITLE
data.table + dtplyr throws `lazy_dt()` error when running skim() 

### ISSUE THREAD

**Issue by rsaporta** [ropensci/skimr#621]
Summary:
* running `skim(DT)` where `DT` is a `data.table` produces pesky warnings. 
* The use of `dplyr` functions on a `data.table` requires some special considerations to avoid typical `lazy_dt()` warnings. 

> Warning: You are using a dplyr method on a raw data.table, which will call the
> * data frame implementation, and is likely to be inefficient.
> *
> * To suppress this message, either generate a data.table translation with
> * `lazy_dt()` or convert to a data frame or tibble with
> * `as.data.frame()`/`as_tibble()`.

# Reproducible example

## Setup
```
library(skimr)
library(data.table)

## ensure warnings are not silenced
options(warn = 1)

## create a simple data.table
DT_letters <- data.table(abc = letters)
```

## skimming works as expected, no warnings
```
skim(DT_letters)
```

## if `dtplyr` is loaded, warnings are thrown
```
library(dtplyr)
skim(DT_letters)
```

**Comment by elinw** [comment]
Is there a sample data set with different kinds of variables that people like to use for data.table examples?

**Comment by elinw** [comment]
Okay I merged in the support data table branch a while ago. So as far as I know the current master addresses this, so I'm closing. If it's not, let me know.
