### ISSUE TITLE
convenience function - stata format

### ISSUE THREAD

**Issue by bjornerstedt** [ropensci/skimr#623]
Skimr is a very powerful tool for generating summary statistics. For quick use and for new users it would be great if it had some convenience functions for common formats. 

Here is the code that I use with skimr to get summary statistics in a Stata format. 

```
sumstats = function(df) {
  sstat = df %>% 
    skim() 
  sstat %>% yank("numeric") %>% 
    mutate(obs = attr(sstat,"data_rows") - n_missing) %>% 
    select(term=skim_variable, obs, mean, sd, min=p0, max=p100) %>% 
    knitr::kable(digits = 2)
}
```

In addition to producing an output in a format I am comfortable with, this small function solves several problems. 

* It removes the 'Variable type: numeric' heading, which is not suitable in published output
* It replaces the 'skim_variable' column heading with 'term', which is better for published output
* It removes the hist column, which my students have problems with when generating pdf from rmarkdown.

Convenience functions like this could be added to skimr either as functions, perhaps with names such as `skim_stata`. It would make skimr easier to use and more convenient, especially in teaching.

**Comment by michaelquinn32** [comment]
Thanks for the suggestion Jonas!

We have worked really hard to make `skimr` more extensible, and you provide a good example about the merits of the approach. That said, these sorts of extensions are better suited to external packages. For example,

*  @elinw has developed several extensions of skimr already, in https://github.com/elinw/skimrextra
*  @rubenarslan has changed the focus towards understanding table metadata https://github.com/rubenarslan/codebook
*  @beanumber has a more portable (i.e. not UTF-8) dependent version of skim for their book, Modern Data Science with R: https://github.com/beanumber/mdsr/blob/ace672f493b0cac467d4b0dd085c02f075250c87/R/themes.R#L37

I'd be happy to provide more guidance to adding your function to your own package or another location that you might find suitable. The "Whole Game" chapter in the R-Pkgs book is a good TLDR to this process. https://r-pkgs.org/whole-game.html

Best wishes,
Michael
