### ISSUE TITLE
Output isn't printing as expected

### ISSUE THREAD

**Issue by hjohns12** [ropensci/skimr#641]
This is what I see when I try to use `skim` today. Using version skimr_2.1.2.

`skim(iris)`
── Data Summary ────────────────────────
                           Values
Name                       iris  
Number of rows             150   
Number of columns          5     
_______________________          
Column type frequency:           
  factor                   1     
  numeric                  4     
________________________         
Group variables            None  

── Variable type: factor ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

── Variable type: numeric ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by michaelquinn32** [comment]
Hi Hope!

Sorry for the issue. Are you on windows? What version of R are you using?

Either way, could your try

```
options(skimr_strip_metadata = FALSE)
```

And try again?

Thanks!

**Comment by hjohns12** [comment]
I'm on a Mac.  When I tried `options(skimr_strip_metadata = FALSE)` everything works as expected. Thanks!

R.version
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out

**Comment by elinw** [comment]
I just got this as well.  I seem to remember that this was an issue also in a prior release and there was an easy fix, will look.

**Comment by elinw** [comment]
I'm going to pin this.

**Comment by pulleyps** [comment]
I am finding that if I run the following, skim() outputs appropriately:

iris %>%
  dplyr::group_by(Species) %>%
  skim()

But when I apply it to the end of a long pipe, skim() does nothing.  I can see it running, but then it stops and doesn't show any output.   If I replace the skim() function at the end with print() then the result prints nicely as expected:    

data <-   starting_data %>%  
     (many commands in pipe) %>%
     skim()

Does skim() not work with long or complicated pipes?  Is it an RStudio setting issue?

**Comment by elinw** [comment]
Hi this is really a different issue in my opinion.   There is no reason skimr should not work in a long series.  Can you please open this as a new issue and past your complete code that isn't working?

**Comment by pulleyps** [comment]
Ok, I opened a new issue.

**Comment by elinw** [comment]
I'm going to close this because I think it is also addressed by the pillar issue.  #676  #654
