### ISSUE TITLE
"Inspiration" links removed from pillar, find a new place in this package?

### ISSUE THREAD

**Issue by krlmlr** [ropensci/skimr#649]
I'm removing the following contents from pillar's readme in https://github.com/r-lib/pillar/pull/267, because they no longer apply:

> ## Inspirations
>
> * [TextPlots](https://github.com/sunetos/TextPlots.jl) for use of Braille
>   characters
>
> * [spark](https://github.com/holman/spark) for use of block characters.
>
> The earliest use of unicode characters to generate sparklines appears to be [from 2009](https://blog.jonudell.net/2009/01/13/fuel-prices-and-pageviews/).
>
> Exercising these ideas to their fullest requires a font with good support for block drawing characters. [PragamataPro](https://fsd.it/shop/fonts/pragmatapro/) is one such font.

Would you like to use some or all of it somewhere in this package?

CC @hadley.

**Comment by michaelquinn32** [comment]
Hi Kirill!

We'd be happy to take ownership of these pieces. Feel free to open a PR.

Thanks!
Michael
