### ISSUE TITLE
Use GitHub release after each CRAN update?

### ISSUE THREAD

**Issue by maelle** [ropensci/skimr#653]
This way the next rOpenSci newsletter can include the update https://ropensci.org/blog/2021/03/16/ropensci-news/

**Comment by michaelquinn32** [comment]
Thanks for the reminder Maelle!

Is anyone else using tools to automate this? Suggestions would be appreciated

**Comment by maelle** [comment]
From what I know

* using https://usethis.r-lib.org/reference/use_release_issue.html when preparing a release as one of the items is creating the GitHub release
* using https://usethis.r-lib.org/reference/use_github_release.html to draft the release

**Comment by michaelquinn32** [comment]
Thanks!
