### ISSUE TITLE
what is the meaning of “top_counts ”？

### ISSUE THREAD

**Issue by A-Pai** [ropensci/skimr#672]
library(rpart)
skimr::skim(cu.summary)

![image](https://user-images.githubusercontent.com/5112397/141082805-e4be5112-799e-427a-90e5-cbb5b466bb52.png)

**Comment by michaelquinn32** [comment]
Hi!

Thanks for the comment.

These are factor variables. In this column we count the levels and show which levels has the highest count. So, for the variable `Country`, in your data `USA` is the most common level, with 49 instances.

Best wishes,
Michael
