### ISSUE TITLE
Replace vignette to reduce dependencies

### ISSUE THREAD

**Issue by michaelquinn32** [ropensci/skimr#675]
We have `sf` as a suggested package, only for illustrating how to extend `skimr` in a vignette. This is a little excessive, and we are seeing CI failures when trying to install `sf`. A simpler example would make everything easier to maintain.

**Comment by elinw** [comment]
I started working on this.  It turned out to be kind of interesting, because that one vignette includes a lot, but at least I have some of it covered.

**Comment by elinw** [comment]
@michaelquinn32  https://rpubs.com/elinw/852868   is most of a new vignette but actually there is an error somewhere. But you get the concept, let me know what you think. I will update once i get rid of the error.
