### ISSUE TITLE
Fix R CMD Check issues

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#683]
Currently I'm getting some issues

````
checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'print'
    ‘n_extra’



checking Rd cross-references ... WARNING
  Missing link or links in documentation object 'print.Rd':
    ‘tbl_format_setup’
  
  See section 'Cross-references' in the 'Writing R Extensions' manual
````

This is the generated line in print.rd that is causing the latter:

`\item{...}{Passed on to \code{\link[=tbl_format_setup]{tbl_format_setup()}}.}`

@michaelquinn32  You have a better sense of the documentation than I do, I think it's happening because we are pulling in from the tidyverse.

**Comment by michaelquinn32** [comment]
I think these are addressed in the outstanding PRs.

Let's merge those and double back to this then.

**Comment by elinw** [comment]
Okay I asked a couple of questions in them, but they look great.
