### ISSUE TITLE
Fix CRAN note

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#688]
We have a  note on CRAN, we need to remove the lazy data reference since we have no data.
But that means we need to decide on whether we can do a new release with some of the new changes/bug fixes or we still have to finish things. @michaelquinn32

**Comment by michaelquinn32** [comment]
Thanks!

I would rather get the note resolved early, so feel free to release.

**Comment by michaelquinn32** [comment]
Plus, looking from the news, I see lots of good features in this version too. It'll be great to get that released.

**Comment by elinw** [comment]
Okay I'll see what I can do this weekend.
