### ISSUE TITLE
Rhub issues

### ISSUE THREAD

**Issue by elinw** [ropensci/skimr#697]
Getting this when running cran check:

> Namespaces in Imports field not imported from:
>      'crayon' 'withr'
>      All declared Imports should be used.
> 
> Gett:
>  Found the following files/directories:
>      'lastMiKTeXException'
> 
But seem not to be the only ones

Can we take the two packages out? 
@michaelquinn32

**Comment by michaelquinn32** [comment]
Great! Both packages are now suggests (used in tests) instead of imports. Thanks!
