### ISSUE TITLE
Is there a way to get the plain text output in RMarkdown?

### ISSUE THREAD

**Issue by ArthurAndrews** [ropensci/skimr#711]
It seems that `skim` understands when it's called from within an RMarkdown chunk and uses a different print method with kable.  This looks great in the document/notebook, but it's harder to read in the RStudio IDE.  Sometimes I would prefer to see the output from the print method that's used in the console in the chunk.  Is there any way to do this?  Thanks for the great package!

I tried the suggested method with chunk options normal_print from the vignette, but it didn't work for me.

![image](https://user-images.githubusercontent.com/65186717/170995197-f77f9b92-e5c5-4a5d-9b2c-c7e0cd168e51.png)

**Comment by elinw** [comment]
That would definitely be a helpful feature, something like print.skimr.console   ... I don't see an obvious way to do this at the moment but perhaps @michaelquinn32 will have an idea.

**Comment by michaelquinn32** [comment]
Hi Arthur!

Glad you like the package.

Set `options(paged.print = FALSE)` to get the original output.

![Screenshot 2022-06-18 125429](https://user-images.githubusercontent.com/3473921/174455350-01d86935-0e60-4462-9cf0-8ff4e3e3ef37.png)

You can also disable it using `paged.print=FALSE` as a chunk option.

Either way, we could probably do more to improve paged output in notebooks. I'll start another issue for that.

Best wishes,
Michael

**Comment by ArthurAndrews** [comment]
This is a great solution.  I'll be using this often.  Thank you very much!

**Comment by ArthurAndrews** [comment]
The `paged.print = FALSE` chunk setting is respected by the RStudio IDE and html_notebook output, but is ignored when I knit to html_document.  It will still print a kable html table.  Any ideas?

**Comment by michaelquinn32** [comment]
Sorry about that issue Arthur. This looks like you're running into:

*  https://github.com/rstudio/rmarkdown/issues/964
*  https://github.com/rstudio/rstudio/issues/1626

I think the easiest issue is to switch from `html_notebook` to `html_document` if you need more control of the rendered output. Your original option `render = knitr::normal_print` seems to be WAI.

Best wishes,
Michael
