### ISSUE TITLE
Submit new version of skimr to CRAN soon?

### ISSUE THREAD

**Issue by DavisVaughan** [ropensci/skimr#721]
I'm running the revdeps for dplyr 1.1.0 and skimr came up, but it seems like the problems were actually already fixed by https://github.com/ropensci/skimr/pull/713.

Are you planning on sending a release in soon?

We are planning on sending in dplyr on January 27th.

Thanks!

**Comment by elinw** [comment]
Yes working on it today.

**Comment by elinw** [comment]
Done!
