### ISSUE TITLE
Summarize character vectors like factors

### ISSUE THREAD

**Issue by jxu** [ropensci/skimr#743]
Readr's `read_csv` reads all strings as characters, with no `stringsAsFactors` switch. This is fine, but when using skimr I've found treating the strings as factors almost always gives more useful results: min/max are string lengths, which isn't useful for categorical levels, while top_counts is much more handy. Maybe there should be a `strings_like_factors` switch which can quickly report top counts instead of min/max length and counts of empty/whitespace. Otherwise the current dplyr method to convert all chars to factors is something like `df %>% mutate(across(where(is.character), factor))`.

**Comment by michaelquinn32** [comment]
Thanks for the suggestion!

We should be able to support this through custom skim functions. Here's an example:

```r
my_skim <- skim_with(character = get_sfl('factor'), append = FALSE)

data.frame(affiliations = c("Dem", "Dem", "Rep", "Rep", "Ind", "Lib")) |>
  my_skim() |>
  print()
```

![image](https://github.com/ropensci/skimr/assets/3473921/9a7f9d05-cf9f-4c69-9e57-0327a44eabb0)

**Comment by jxu** [comment]
Nice solution. I think it is a suitable option.
